const AnimalDataset = [
  {
    "Animal": "Aardvark",
    "Height (cm)": "105-130",
    "Weight (kg)": "40-65",
    "Color": "Grey",
    "Lifespan (years)": "20-30",
    "Diet": "Insectivore",
    "Habitat": "Savannas, Grasslands",
    "Predators": "Lions, Hyenas",
    "Countries Found": "Africa",
    "Conservation Status": "Least Concern",
    "Family": "Orycteropodidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "African Elephant",
    "Height (cm)": "270-310",
    "Weight (kg)": "2700-6000",
    "Color": "Grey",
    "Lifespan (years)": "60-70",
    "Diet": "Herbivore",
    "Habitat": "Savannah, Forest",
    "Predators": "Lions, Hyenas",
    "Countries Found": "Africa",
    "Conservation Status": "Vulnerable",
    "Family": "Elephantidae",
    "Social Structure": "Herd-based"
  },
  {
    "Animal": "American Bison",
    "Height (cm)": "152-186",
    "Weight (kg)": "318-1,000",
    "Color": "Brown",
    "Lifespan (years)": "15-20",
    "Diet": "Herbivore",
    "Habitat": "Grasslands, Plains",
    "Predators": "Wolves, Grizzly Bears",
    "Countries Found": "North America",
    "Conservation Status": "Near Threatened",
    "Family": "Bovidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Anteater",
    "Height (cm)": "52-91",
    "Weight (kg)": "22-41",
    "Color": "Brown, White",
    "Lifespan (years)": "15-20",
    "Diet": "Insectivore",
    "Habitat": "Grasslands, Forests",
    "Predators": "Jaguars, Pumas",
    "Countries Found": "Central and South America",
    "Conservation Status": "Least Concern",
    "Family": "Myrmecophagidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Asian Elephant",
    "Height (cm)": "200-300",
    "Weight (kg)": "2000-5000",
    "Color": "Grey",
    "Lifespan (years)": "60-80",
    "Diet": "Herbivore",
    "Habitat": "Grasslands, Forests",
    "Predators": "Tigers, Leopards",
    "Countries Found": "Asia (Southeast)",
    "Conservation Status": "Endangered",
    "Family": "Elephantidae",
    "Social Structure": "Herd-based"
  },
  {
    "Animal": "Atlantic Spotted Dolphin",
    "Height (cm)": "200-250",
    "Weight (kg)": "120-140",
    "Color": "Gray, White",
    "Lifespan (years)": "20-25",
    "Diet": "Carnivore",
    "Habitat": "Oceans, Coastal Areas",
    "Predators": "Sharks, Orcas",
    "Countries Found": "Worldwide",
    "Conservation Status": "Least Concern",
    "Family": "Delphinidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Australian Fur Seal",
    "Height (cm)": "112-160",
    "Weight (kg)": "18-40",
    "Color": "Brown, Gray",
    "Lifespan (years)": "14-17",
    "Diet": "Carnivore",
    "Habitat": "Coastal Waters",
    "Predators": "Sharks, Orcas",
    "Countries Found": "Australia, New Zealand",
    "Conservation Status": "Least Concern",
    "Family": "Otariidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Baird's Tapir",
    "Height (cm)": "76-107",
    "Weight (kg)": "150-400",
    "Color": "Brown, Black",
    "Lifespan (years)": "25-30",
    "Diet": "Herbivore",
    "Habitat": "Rainforests, Grasslands",
    "Predators": "Jaguars, Crocodiles",
    "Countries Found": "Central and South America",
    "Conservation Status": "Endangered",
    "Family": "Tapiridae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Basking Shark",
    "Height (cm)": "Up to 1100",
    "Weight (kg)": "400-700",
    "Color": "Gray, Brown",
    "Lifespan (years)": "20-25",
    "Diet": "Carnivore",
    "Habitat": "Oceans",
    "Predators": "Orcas, Great White Sharks",
    "Countries Found": "Worldwide",
    "Conservation Status": "Vulnerable",
    "Family": "Cetorhinidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Blue Morpho Butterfly",
    "Height (cm)": "Up to 15",
    "Weight (kg)": "Up to 0.028",
    "Color": "Blue",
    "Lifespan (years)": "1-2 weeks",
    "Diet": "Herbivore",
    "Habitat": "Rainforests",
    "Predators": "Birds, Bats",
    "Countries Found": "Central and South America",
    "Conservation Status": "Not Evaluated",
    "Family": "Nymphalidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Blue-Ringed Octopus",
    "Height (cm)": "Up to 20",
    "Weight (kg)": "Up to 0.3",
    "Color": "Blue, Brown",
    "Lifespan (years)": "6-8 months",
    "Diet": "Carnivore",
    "Habitat": "Coral Reefs, Tide Pools",
    "Predators": "Larger Fish",
    "Countries Found": "Indo-Pacific region",
    "Conservation Status": "Near Threatened",
    "Family": "Octopodidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Bonobo",
    "Height (cm)": "Up to 150",
    "Weight (kg)": "30-40",
    "Color": "Black",
    "Lifespan (years)": "40-60",
    "Diet": "Omnivore",
    "Habitat": "Rainforests",
    "Predators": "Leopards, Humans",
    "Countries Found": "Democratic Republic of Congo",
    "Conservation Status": "Endangered",
    "Family": "Hominidae",
    "Social Structure": "Social groups"
  },
  {
    "Animal": "Bornean Orangutan",
    "Height (cm)": "96-150",
    "Weight (kg)": "30-82",
    "Color": "Reddish-brown",
    "Lifespan (years)": "35-45",
    "Diet": "Omnivore",
    "Habitat": "Rainforests",
    "Predators": "Tigers, Humans",
    "Countries Found": "Borneo",
    "Conservation Status": "Critically Endangered",
    "Family": "Hominidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Bottlenose Dolphin",
    "Height (cm)": "200-400",
    "Weight (kg)": "150-650",
    "Color": "Grey",
    "Lifespan (years)": "20-50",
    "Diet": "Carnivore",
    "Habitat": "Oceans",
    "Predators": "Sharks, Orcas",
    "Countries Found": "Oceans worldwide",
    "Conservation Status": "Least Concern",
    "Family": "Delphinidae",
    "Social Structure": "Social pods"
  },
  {
    "Animal": "Brown Bear",
    "Height (cm)": "70-120",
    "Weight (kg)": "70-780",
    "Color": "Brown",
    "Lifespan (years)": "20-30",
    "Diet": "Omnivore",
    "Habitat": "Forests, Mountains",
    "Predators": "Wolves, Tigers",
    "Countries Found": "North America, Europe, Asia",
    "Conservation Status": "Least Concern",
    "Family": "Ursidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Burmese Python",
    "Height (cm)": "Up to 460",
    "Weight (kg)": "Up to 90",
    "Color": "Brown, Black",
    "Lifespan (years)": "20-25",
    "Diet": "Carnivore",
    "Habitat": "Grasslands, Forests",
    "Predators": "Leopards, Hawksbills",
    "Countries Found": "Southeast Asia, South Asia, Indonesia",
    "Conservation Status": "Least Concern",
    "Family": "Pythonidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Chimpanzee",
    "Height (cm)": "Up to 160",
    "Weight (kg)": "26-70",
    "Color": "Black",
    "Lifespan (years)": "40-50",
    "Diet": "Omnivore",
    "Habitat": "Rainforests, Grasslands",
    "Predators": "Leopards, Humans",
    "Countries Found": "Central and West Africa",
    "Conservation Status": "Endangered",
    "Family": "Hominidae",
    "Social Structure": "Social groups"
  },
  {
    "Animal": "Coelacanth",
    "Height (cm)": "Up to 200",
    "Weight (kg)": "Up to 90",
    "Color": "Brown, Grey",
    "Lifespan (years)": "Up to 60",
    "Diet": "Carnivore",
    "Habitat": "Deep-sea, Caves",
    "Predators": "Sharks, Humans",
    "Countries Found": "Western Indian Ocean",
    "Conservation Status": "Not Evaluated",
    "Family": "Latimeriidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Common Dolphin",
    "Height (cm)": "200-250",
    "Weight (kg)": "100-135",
    "Color": "Gray, Yellow",
    "Lifespan (years)": "20-25",
    "Diet": "Carnivore",
    "Habitat": "Oceans, Coastal Areas",
    "Predators": "Sharks, Orcas",
    "Countries Found": "Worldwide",
    "Conservation Status": "Least Concern",
    "Family": "Delphinidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Dugong",
    "Height (cm)": "Up to 300",
    "Weight (kg)": "Up to 420",
    "Color": "Gray",
    "Lifespan (years)": "70-80",
    "Diet": "Herbivore",
    "Habitat": "Coastal Waters, Seagrass",
    "Predators": "Sharks, Orcas",
    "Countries Found": "Indian Ocean, Western Pacific",
    "Conservation Status": "Vulnerable",
    "Family": "Dugongidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Eastern Gorilla",
    "Height (cm)": "140-188",
    "Weight (kg)": "73-204",
    "Color": "Black",
    "Lifespan (years)": "40-50",
    "Diet": "Herbivore",
    "Habitat": "Rainforests",
    "Predators": "Leopards, Humans",
    "Countries Found": "Democratic Republic of Congo",
    "Conservation Status": "Endangered",
    "Family": "Hominidae",
    "Social Structure": "Social groups"
  },
  {
    "Animal": "Echidna",
    "Height (cm)": "30-45",
    "Weight (kg)": "2.5-6.5",
    "Color": "Brown, Tan",
    "Lifespan (years)": "15-20",
    "Diet": "Insectivore",
    "Habitat": "Forests, Grasslands",
    "Predators": "Dingoes, Eagles",
    "Countries Found": "Australia, New Guinea",
    "Conservation Status": "Least Concern",
    "Family": "Tachyglossidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Flying Fox",
    "Height (cm)": "Up to 40",
    "Weight (kg)": "Up to 1.1",
    "Color": "Brown, Gray",
    "Lifespan (years)": "15-23",
    "Diet": "Herbivore",
    "Habitat": "Forests",
    "Predators": "Birds of Prey",
    "Countries Found": "Asia, Australia",
    "Conservation Status": "Least Concern",
    "Family": "Pteropodidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Galapagos Tortoise",
    "Height (cm)": "Up to 183",
    "Weight (kg)": "Up to 417",
    "Color": "Brown, Grey",
    "Lifespan (years)": "100-150",
    "Diet": "Herbivore",
    "Habitat": "Galapagos Islands",
    "Predators": "Humans, Rats",
    "Countries Found": "Galapagos Islands",
    "Conservation Status": "Vulnerable",
    "Family": "Testudinidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Gaur",
    "Height (cm)": "180-300",
    "Weight (kg)": "600-1300",
    "Color": "Dark Brown, Black",
    "Lifespan (years)": "20-25",
    "Diet": "Herbivore",
    "Habitat": "Grasslands, Forests",
    "Predators": "Tigers, Leopards",
    "Countries Found": "Southeast Asia, South Asia",
    "Conservation Status": "Vulnerable",
    "Family": "Bovidae",
    "Social Structure": "Herd-based"
  },
  {
    "Animal": "Gharial",
    "Height (cm)": "Up to 600",
    "Weight (kg)": "Up to 1500",
    "Color": "Brownish-gray",
    "Lifespan (years)": "40-60",
    "Diet": "Carnivore",
    "Habitat": "Rivers, Lakes",
    "Predators": "Crocodiles, Tigers",
    "Countries Found": "Indian subcontinent",
    "Conservation Status": "Critically Endangered",
    "Family": "Gavialidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Giant Panda",
    "Height (cm)": "70-90",
    "Weight (kg)": "70-125",
    "Color": "Black, White",
    "Lifespan (years)": "20-30",
    "Diet": "Herbivore",
    "Habitat": "Temperate Broadleaf Forests",
    "Predators": "Snow Leopards",
    "Countries Found": "China",
    "Conservation Status": "Endangered",
    "Family": "Ursidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Glass Frog",
    "Height (cm)": "2.2-7.7",
    "Weight (kg)": "Up to 0.03",
    "Color": "Green, Transparent",
    "Lifespan (years)": "10-14 days",
    "Diet": "Insectivore",
    "Habitat": "Rainforests",
    "Predators": "Birds, Snakes",
    "Countries Found": "Central and South America",
    "Conservation Status": "Least Concern",
    "Family": "Centrolenidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Goblin Shark",
    "Height (cm)": "Up to 320",
    "Weight (kg)": "Up to 210",
    "Color": "Pinkish-gray",
    "Lifespan (years)": "30-35",
    "Diet": "Carnivore",
    "Habitat": "Deep-sea",
    "Predators": "Larger Fish, Other Sharks",
    "Countries Found": "Worldwide",
    "Conservation Status": "Data Deficient",
    "Family": "Mitsukurinidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Great White Shark",
    "Height (cm)": "Up to 610",
    "Weight (kg)": "Up to 2268",
    "Color": "Grey",
    "Lifespan (years)": "30-40",
    "Diet": "Carnivore",
    "Habitat": "Oceans",
    "Predators": "Orcas",
    "Countries Found": "Oceans worldwide",
    "Conservation Status": "Vulnerable",
    "Family": "Lamnidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Green Sea Turtle",
    "Height (cm)": "Up to 120",
    "Weight (kg)": "Up to 200",
    "Color": "Greenish-brown",
    "Lifespan (years)": "80-100",
    "Diet": "Herbivore",
    "Habitat": "Oceans, Coastal Areas",
    "Predators": "Predatory Fish",
    "Countries Found": "Oceans worldwide",
    "Conservation Status": "Endangered",
    "Family": "Cheloniidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Grevy's Zebra",
    "Height (cm)": "130-160",
    "Weight (kg)": "350-450",
    "Color": "White, Black",
    "Lifespan (years)": "20-30",
    "Diet": "Herbivore",
    "Habitat": "Grasslands",
    "Predators": "Lions, Hyenas",
    "Countries Found": "Eastern Africa",
    "Conservation Status": "Endangered",
    "Family": "Equidae",
    "Social Structure": "Herd-based"
  },
  {
    "Animal": "Hagfish",
    "Height (cm)": "Up to 127",
    "Weight (kg)": "Up to 0.6",
    "Color": "Pinkish-gray",
    "Lifespan (years)": "Up to 30",
    "Diet": "Carnivore",
    "Habitat": "Deep-sea",
    "Predators": "Not Applicable",
    "Countries Found": "Worldwide",
    "Conservation Status": "Data Deficient",
    "Family": "Myxinidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Harpy Eagle",
    "Height (cm)": "86-107",
    "Weight (kg)": "4.5-9",
    "Color": "Black, White",
    "Lifespan (years)": "25-35",
    "Diet": "Carnivore",
    "Habitat": "Rainforests",
    "Predators": "Jaguars, Snakes",
    "Countries Found": "Central and South America",
    "Conservation Status": "Near Threatened",
    "Family": "Accipitridae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Hippopotamus",
    "Height (cm)": "120-160",
    "Weight (kg)": "1300-3200",
    "Color": "Grey",
    "Lifespan (years)": "40-50",
    "Diet": "Herbivore",
    "Habitat": "Rivers, Lakes",
    "Predators": "Lions, Crocodiles",
    "Countries Found": "Sub-Saharan Africa",
    "Conservation Status": "Vulnerable",
    "Family": "Hippopotamidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Humpback Whale",
    "Height (cm)": "Up to 1700",
    "Weight (kg)": "Up to 30000",
    "Color": "Black, White",
    "Lifespan (years)": "45-50",
    "Diet": "Omnivore",
    "Habitat": "Oceans",
    "Predators": "Orcas",
    "Countries Found": "Worldwide",
    "Conservation Status": "Least Concern",
    "Family": "Balaenopteridae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Indri",
    "Height (cm)": "Up to 70",
    "Weight (kg)": "Up to 6",
    "Color": "Black, White",
    "Lifespan (years)": "15-18",
    "Diet": "Herbivore",
    "Habitat": "Rainforests",
    "Predators": "Fossa, Birds of Prey",
    "Countries Found": "Madagascar",
    "Conservation Status": "Critically Endangered",
    "Family": "Indridae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "King Cobra",
    "Height (cm)": "Up to 550",
    "Weight (kg)": "Up to 9",
    "Color": "Olive-green",
    "Lifespan (years)": "20-30",
    "Diet": "Carnivore",
    "Habitat": "Grasslands, Forests",
    "Predators": "Birds, Snakes",
    "Countries Found": "Southeast Asia, South Asia",
    "Conservation Status": "Vulnerable",
    "Family": "Elapidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Kiwi",
    "Height (cm)": "25-46",
    "Weight (kg)": "1.0-3.3",
    "Color": "Brown",
    "Lifespan (years)": "25-50",
    "Diet": "Omnivore",
    "Habitat": "Forests",
    "Predators": "Stoats, Cats",
    "Countries Found": "New Zealand",
    "Conservation Status": "Vulnerable",
    "Family": "Apterygidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Komodo Dragon",
    "Height (cm)": "Up to 300",
    "Weight (kg)": "Up to 90",
    "Color": "Grey",
    "Lifespan (years)": "20-30",
    "Diet": "Carnivore",
    "Habitat": "Islands, Grasslands",
    "Predators": "Humans, Larger Predators",
    "Countries Found": "Indonesia",
    "Conservation Status": "Vulnerable",
    "Family": "Varanidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Leafy Sea Dragon",
    "Height (cm)": "Up to 35",
    "Weight (kg)": "Up to 0.5",
    "Color": "Brown, Green",
    "Lifespan (years)": "Up to 10",
    "Diet": "Carnivore",
    "Habitat": "Seaweed Beds",
    "Predators": "Fish, Octopuses",
    "Countries Found": "Southern Australia",
    "Conservation Status": "Near Threatened",
    "Family": "Syngnathidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Lemur",
    "Height (cm)": "30-50",
    "Weight (kg)": "0.6-3.5",
    "Color": "Various",
    "Lifespan (years)": "15-25",
    "Diet": "Omnivore",
    "Habitat": "Rainforests, Madagascar",
    "Predators": "Fossa, Hawks",
    "Countries Found": "Madagascar",
    "Conservation Status": "Vulnerable",
    "Family": "Lemuridae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Lyrebird",
    "Height (cm)": "80-100",
    "Weight (kg)": "0.9-1.2",
    "Color": "Brown, Black",
    "Lifespan (years)": "15-20",
    "Diet": "Omnivore",
    "Habitat": "Rainforests",
    "Predators": "Birds of Prey, Dingoes",
    "Countries Found": "Australia",
    "Conservation Status": "Least Concern",
    "Family": "Menuridae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Manatee",
    "Height (cm)": "300-400",
    "Weight (kg)": "400-590",
    "Color": "Gray, Brown",
    "Lifespan (years)": "40-60",
    "Diet": "Herbivore",
    "Habitat": "Rivers, Coastal Areas",
    "Predators": "Alligators, Sharks",
    "Countries Found": "North, Central, and South America",
    "Conservation Status": "Vulnerable",
    "Family": "Trichechidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Mandrill",
    "Height (cm)": "Up to 75",
    "Weight (kg)": "Up to 55",
    "Color": "Brown, Green",
    "Lifespan (years)": "20-40",
    "Diet": "Omnivore",
    "Habitat": "Rainforests",
    "Predators": "Leopards, Humans",
    "Countries Found": "Central Africa",
    "Conservation Status": "Vulnerable",
    "Family": "Cercopithecidae",
    "Social Structure": "Social groups"
  },
  {
    "Animal": "Mantis Shrimp",
    "Height (cm)": "Up to 30",
    "Weight (kg)": "Up to 2.7",
    "Color": "Various",
    "Lifespan (years)": "Up to 20",
    "Diet": "Carnivore",
    "Habitat": "Coral Reefs",
    "Predators": "Larger Fish",
    "Countries Found": "Oceans worldwide",
    "Conservation Status": "Not Evaluated",
    "Family": "Stomatopoda",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Mountain Gorilla",
    "Height (cm)": "120-200",
    "Weight (kg)": "70-200",
    "Color": "Black, Brown",
    "Lifespan (years)": "35-40",
    "Diet": "Herbivore",
    "Habitat": "Rainforests, Mountains",
    "Predators": "Leopards, Humans",
    "Countries Found": "Democratic Republic of Congo, Uganda",
    "Conservation Status": "Endangered",
    "Family": "Hominidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Narwhal",
    "Height (cm)": "Up to 500",
    "Weight (kg)": "Up to 1600",
    "Color": "Gray, Mottled White",
    "Lifespan (years)": "50-60",
    "Diet": "Carnivore",
    "Habitat": "Arctic Waters",
    "Predators": "Polar Bears, Orcas",
    "Countries Found": "Arctic",
    "Conservation Status": "Near Threatened",
    "Family": "Monodontidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Nudibranch",
    "Height (cm)": "Up to 30",
    "Weight (kg)": "Up to 1",
    "Color": "Various",
    "Lifespan (years)": "Up to 10",
    "Diet": "Carnivore",
    "Habitat": "Oceans, Coral Reefs",
    "Predators": "Sea Anemones, Predatory Fish",
    "Countries Found": "Oceans worldwide",
    "Conservation Status": "Not Evaluated",
    "Family": "Nudibranchia",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Numbat",
    "Height (cm)": "35-45",
    "Weight (kg)": "0.32-1",
    "Color": "Red, White",
    "Lifespan (years)": "Up to 5",
    "Diet": "Insectivore",
    "Habitat": "Eucalyptus Forests",
    "Predators": "Foxes, Cats",
    "Countries Found": "Western Australia",
    "Conservation Status": "Endangered",
    "Family": "Myrmecobiidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Okapi",
    "Height (cm)": "200-250",
    "Weight (kg)": "200-350",
    "Color": "Brown, White",
    "Lifespan (years)": "20-30",
    "Diet": "Herbivore",
    "Habitat": "Central Africa",
    "Predators": "Leopards, Lions",
    "Countries Found": "Democratic Republic of Congo",
    "Conservation Status": "Endangered",
    "Family": "Giraffidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Orangutan",
    "Height (cm)": "Up to 160",
    "Weight (kg)": "30-82",
    "Color": "Reddish-brown",
    "Lifespan (years)": "30-45",
    "Diet": "Omnivore",
    "Habitat": "Rainforests",
    "Predators": "Tigers, Humans",
    "Countries Found": "Indonesia, Malaysia",
    "Conservation Status": "Critically Endangered",
    "Family": "Hominidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Peacock Mantis Shrimp",
    "Height (cm)": "Up to 18",
    "Weight (kg)": "Up to 0.4",
    "Color": "Various",
    "Lifespan (years)": "Up to 20",
    "Diet": "Carnivore",
    "Habitat": "Coral Reefs",
    "Predators": "Fish, Crustaceans",
    "Countries Found": "Indo-Pacific region",
    "Conservation Status": "Not Evaluated",
    "Family": "Gonodactylidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Polar Bear",
    "Height (cm)": "Up to 160",
    "Weight (kg)": "Up to 700",
    "Color": "White",
    "Lifespan (years)": "25-30",
    "Diet": "Carnivore",
    "Habitat": "Arctic",
    "Predators": "Orcas",
    "Countries Found": "Arctic",
    "Conservation Status": "Vulnerable",
    "Family": "Ursidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Proboscis Monkey",
    "Height (cm)": "45-75",
    "Weight (kg)": "14-24",
    "Color": "Orange, Brown",
    "Lifespan (years)": "Up to 15",
    "Diet": "Herbivore",
    "Habitat": "Mangroves, Rainforests",
    "Predators": "Clouded Leopards",
    "Countries Found": "Borneo, Malaysia",
    "Conservation Status": "Endangered",
    "Family": "Cercopithecidae",
    "Social Structure": "Social groups"
  },
  {
    "Animal": "Red Kangaroo",
    "Height (cm)": "140-180",
    "Weight (kg)": "18-95",
    "Color": "Brown, Red",
    "Lifespan (years)": "Up to 23",
    "Diet": "Herbivore",
    "Habitat": "Grasslands",
    "Predators": "Dingoes, Eagles",
    "Countries Found": "Australia",
    "Conservation Status": "Least Concern",
    "Family": "Macropodidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Red-Eyed Tree Frog",
    "Height (cm)": "5.1-7.5",
    "Weight (kg)": "Up to 0.1",
    "Color": "Green, Red",
    "Lifespan (years)": "Up to 5",
    "Diet": "Insectivore",
    "Habitat": "Rainforests",
    "Predators": "Snakes, Birds",
    "Countries Found": "Central America",
    "Conservation Status": "Least Concern",
    "Family": "Hylidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Saola",
    "Height (cm)": "Up to 90",
    "Weight (kg)": "Up to 100",
    "Color": "Brown, White",
    "Lifespan (years)": "Up to 21",
    "Diet": "Herbivore",
    "Habitat": "Forests",
    "Predators": "Tigers, Leopards",
    "Countries Found": "Vietnam, Laos",
    "Conservation Status": "Critically Endangered",
    "Family": "Bovidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Shortfin Mako Shark",
    "Height (cm)": "Up to 394",
    "Weight (kg)": "Up to 800",
    "Color": "Metallic Blue",
    "Lifespan (years)": "28-35",
    "Diet": "Carnivore",
    "Habitat": "Oceans",
    "Predators": "Larger Sharks",
    "Countries Found": "Worldwide",
    "Conservation Status": "Vulnerable",
    "Family": "Lamnidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Slow Loris",
    "Height (cm)": "20-38",
    "Weight (kg)": "0.3-1.6",
    "Color": "Yellowish-Brown",
    "Lifespan (years)": "20-24",
    "Diet": "Omnivore",
    "Habitat": "Forests",
    "Predators": "Birds, Snakes",
    "Countries Found": "Southeast Asia",
    "Conservation Status": "Vulnerable",
    "Family": "Lorisidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Sperm Whale",
    "Height (cm)": "Up to 2056",
    "Weight (kg)": "Up to 57000",
    "Color": "Gray",
    "Lifespan (years)": "50-60",
    "Diet": "Carnivore",
    "Habitat": "Oceans",
    "Predators": "Orcas",
    "Countries Found": "Worldwide",
    "Conservation Status": "Vulnerable",
    "Family": "Physeteridae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Squirrel Monkey",
    "Height (cm)": "25-35",
    "Weight (kg)": "0.5-1",
    "Color": "Yellowish-Orange, Black",
    "Lifespan (years)": "Up to 20",
    "Diet": "Omnivore",
    "Habitat": "Rainforests",
    "Predators": "Snakes, Hawks",
    "Countries Found": "Central and South America",
    "Conservation Status": "Least Concern",
    "Family": "Cebidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Sumatran Orangutan",
    "Height (cm)": "66-100",
    "Weight (kg)": "23-56",
    "Color": "Reddish-Brown",
    "Lifespan (years)": "30-50",
    "Diet": "Omnivore",
    "Habitat": "Rainforests",
    "Predators": "Tigers, Humans",
    "Countries Found": "Sumatra",
    "Conservation Status": "Critically Endangered",
    "Family": "Hominidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Sumatran Rhino",
    "Height (cm)": "100-145",
    "Weight (kg)": "750-950",
    "Color": "Reddish-Brown",
    "Lifespan (years)": "30-45",
    "Diet": "Herbivore",
    "Habitat": "Rainforests",
    "Predators": "Tigers, Humans",
    "Countries Found": "Southeast Asia",
    "Conservation Status": "Critically Endangered",
    "Family": "Rhinocerotidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Sumatran Rhinoceros",
    "Height (cm)": "112-145",
    "Weight (kg)": "500-950",
    "Color": "Brown",
    "Lifespan (years)": "35-40",
    "Diet": "Herbivore",
    "Habitat": "Rainforests",
    "Predators": "Tigers, Humans",
    "Countries Found": "Southeast Asia",
    "Conservation Status": "Critically Endangered",
    "Family": "Rhinocerotidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Sumatran Tiger",
    "Height (cm)": "70-87",
    "Weight (kg)": "47-121",
    "Color": "Orange, Black Stripes",
    "Lifespan (years)": "15-20",
    "Diet": "Carnivore",
    "Habitat": "Rainforests",
    "Predators": "Leopards, Humans",
    "Countries Found": "Sumatra",
    "Conservation Status": "Critically Endangered",
    "Family": "Felidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Sun Bear",
    "Height (cm)": "120-150",
    "Weight (kg)": "27-80",
    "Color": "Black",
    "Lifespan (years)": "25-30",
    "Diet": "Omnivore",
    "Habitat": "Tropical Forests",
    "Predators": "Tigers, Leopards",
    "Countries Found": "Southeast Asia",
    "Conservation Status": "Vulnerable",
    "Family": "Ursidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Tapir",
    "Height (cm)": "70-120",
    "Weight (kg)": "150-400",
    "Color": "Brown, Black",
    "Lifespan (years)": "25-30",
    "Diet": "Herbivore",
    "Habitat": "Rainforests, Grasslands",
    "Predators": "Jaguars, Crocodiles",
    "Countries Found": "South and Central America",
    "Conservation Status": "Vulnerable",
    "Family": "Tapiridae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Tufted Puffin",
    "Height (cm)": "35-41",
    "Weight (kg)": "0.4-1",
    "Color": "Black, White",
    "Lifespan (years)": "Up to 20",
    "Diet": "Carnivore",
    "Habitat": "Coastal Areas",
    "Predators": "Eagles, Falcons",
    "Countries Found": "North Pacific",
    "Conservation Status": "Least Concern",
    "Family": "Alcidae",
    "Social Structure": "Social groups"
  },
  {
    "Animal": "Vaquita",
    "Height (cm)": "Up to 150",
    "Weight (kg)": "Up to 55",
    "Color": "Grey, White",
    "Lifespan (years)": "20-21",
    "Diet": "Carnivore",
    "Habitat": "Gulf of California",
    "Predators": "Nets, Sharks",
    "Countries Found": "Gulf of California, Mexico",
    "Conservation Status": "Critically Endangered",
    "Family": "Phocoenidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Walrus",
    "Height (cm)": "Up to 3200",
    "Weight (kg)": "Up to 1200",
    "Color": "Brown",
    "Lifespan (years)": "40-50",
    "Diet": "Carnivore",
    "Habitat": "Arctic, Coastal Areas",
    "Predators": "Polar Bears, Orcas",
    "Countries Found": "Arctic, Subarctic",
    "Conservation Status": "Least Concern",
    "Family": "Odobenidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Warthog",
    "Height (cm)": "85-150",
    "Weight (kg)": "60-150",
    "Color": "Brown, Black",
    "Lifespan (years)": "15-20",
    "Diet": "Omnivore",
    "Habitat": "Savannahs, Grasslands",
    "Predators": "Lions, Leopards",
    "Countries Found": "Sub-Saharan Africa",
    "Conservation Status": "Least Concern",
    "Family": "Suidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Water Buffalo",
    "Height (cm)": "200-300",
    "Weight (kg)": "300-1200",
    "Color": "Dark Gray",
    "Lifespan (years)": "20-25",
    "Diet": "Herbivore",
    "Habitat": "Grasslands, Wetlands",
    "Predators": "Tigers, Crocodiles",
    "Countries Found": "Asia, Africa",
    "Conservation Status": "Least Concern",
    "Family": "Bovidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Western Lowland Gorilla",
    "Height (cm)": "140-200",
    "Weight (kg)": "68-181",
    "Color": "Black",
    "Lifespan (years)": "30-40",
    "Diet": "Herbivore",
    "Habitat": "Rainforests",
    "Predators": "Leopards, Humans",
    "Countries Found": "Central Africa",
    "Conservation Status": "Critically Endangered",
    "Family": "Hominidae",
    "Social Structure": "Social groups"
  },
  {
    "Animal": "White Rhinoceros",
    "Height (cm)": "1400-2300",
    "Weight (kg)": "1800-2500",
    "Color": "Gray",
    "Lifespan (years)": "40-50",
    "Diet": "Herbivore",
    "Habitat": "Grasslands",
    "Predators": "Lions, Hyenas",
    "Countries Found": "Eastern and Southern Africa",
    "Conservation Status": "Near Threatened",
    "Family": "Rhinocerotidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Wildebeest",
    "Height (cm)": "170-250",
    "Weight (kg)": "200-390",
    "Color": "Gray, Black",
    "Lifespan (years)": "20-25",
    "Diet": "Herbivore",
    "Habitat": "Grasslands",
    "Predators": "Lions, Crocodiles",
    "Countries Found": "Eastern and Southern Africa",
    "Conservation Status": "Least Concern",
    "Family": "Bovidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Yak",
    "Height (cm)": "140-160",
    "Weight (kg)": "500-1200",
    "Color": "Brown, Black",
    "Lifespan (years)": "20-25",
    "Diet": "Herbivore",
    "Habitat": "Mountains",
    "Predators": "Snow Leopards, Wolves",
    "Countries Found": "Himalayas, Central Asia",
    "Conservation Status": "Least Concern",
    "Family": "Bovidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Yeti Crab",
    "Height (cm)": "Up to 15",
    "Weight (kg)": "Up to 0.5",
    "Color": "White, Hairy",
    "Lifespan (years)": "Up to 20",
    "Diet": "Omnivore",
    "Habitat": "Hydrothermal Vents",
    "Predators": "Not Applicable",
    "Countries Found": "Pacific Ocean",
    "Conservation Status": "Not Evaluated",
    "Family": "Kiwaidae",
    "Social Structure": "Solitary"
  },
  {
    "Animal": "Zebra",
    "Height (cm)": "220-340",
    "Weight (kg)": "400-900",
    "Color": "Black, White",
    "Lifespan (years)": "20-25",
    "Diet": "Herbivore",
    "Habitat": "Grasslands",
    "Predators": "Lions, Hyenas",
    "Countries Found": "Africa",
    "Conservation Status": "Least Concern",
    "Family": "Equidae",
    "Social Structure": "Group-based"
  },
  {
    "Animal": "Zebra Shark",
    "Height (cm)": "Up to 330",
    "Weight (kg)": "Up to 32",
    "Color": "Brown, Yellowish",
    "Lifespan (years)": "25-30",
    "Diet": "Carnivore",
    "Habitat": "Coral Reefs",
    "Predators": "Larger Fish",
    "Countries Found": "Indo-Pacific region",
    "Conservation Status": "Endangered",
    "Family": "Stegostomatidae",
    "Social Structure": "Solitary"
  }
]